version: '3.7'

services:
  pdms_db:
    image: mysql:5.7
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdms
      MYSQL_USER: root
    ports:
      - 3306:3306
    volumes:
      - ./pdms_dump.sql:/docker-entrypoint-initdb.d/pdms_dump.sql

  web:
    image: pdms02:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - pdms_db
    volumes:
      - /data/web 
